#include<iostream>
#include<math.h>
using namespace std;

/*int modmul(int m,int e,int n) {
    int c=m;
    for(int i=1;i<e;i++)
        c=fmod(c*m,n);
    return c;
}*/
int modmul(int m,int e,int n) {
    int rev = 0;
    int c=0;
    while (e > 0)
    {
        rev <<= 1;
        if (e & 1 == 1)
            rev ^= 1;
        e >>= 1;
        c++;        
    }
    int d=1;
    while(c>0) {
        d=fmod(d*d,n);
        if(rev&1==1)
            d=fmod(d*m,n);
        rev>>=1;
        c--;
    }
    return d;
}
int main() 
{ 
    int p,alpha;
    int Xa,Xb,Ya,Yb,KeyA,KeyB; 
    cout<<"Enter the value of Prime number : ";
    cin>>p;
    cout<<"Enter the value of Alpha (primitive root of p) : ";
    cin>>alpha;
    cout<<"Enter the private key Xa for A : ";
    cin>>Xa;
    Ya = modmul(alpha,Xa,p);
    cout<<"Enter the private key Xb for B : ";
    cin>>Xb;
    Yb = modmul(alpha,Xb,p);
    cout<<"\nPublic Key of A : "<<Ya<<"\nPublic Key of B : "<<Yb;
    KeyA = modmul(Yb,Xa,p);
    KeyB = modmul(Ya,Xb,p);
    cout<<"\n\nShared Secret key Generated by A : "<<KeyA<<"\nShared Secret key Generated by B : "<<KeyB<<endl;
}